# Generated by Django 4.0.3 on 2022-04-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('find_url', models.URLField()),
                ('domain', models.URLField()),
                ('create_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
                ('country', models.CharField(max_length=100)),
                ('is_dead', models.BooleanField()),
                ('a', models.CharField(max_length=100)),
                ('ns', models.URLField()),
                ('cname', models.URLField()),
                ('mx', models.URLField()),
                ('txt', models.TextField()),
            ],
        ),
    ]
