# Generated by Django 4.0.3 on 2022-04-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('find_url', models.URLField(db_column='найденный url', unique=True)),
                ('domain', models.URLField(blank=True, db_column='domain', null=True)),
                ('create_date', models.DateField(blank=True, db_column='create_date', null=True)),
                ('update_date', models.DateField(blank=True, db_column='update_date', null=True)),
                ('country', models.CharField(blank=True, db_column='country', max_length=25)),
                ('is_dead', models.BooleanField(blank=True, db_column='isDead', null=True)),
                ('a', models.TextField(blank=True, db_column='A')),
                ('ns', models.TextField(blank=True, db_column='NS')),
                ('cname', models.TextField(blank=True, db_column='CNAME')),
                ('mx', models.TextField(blank=True, db_column='MX')),
                ('txt', models.TextField(blank=True, db_column='TXT')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.URLField(unique=True)),
                ('find_urls', models.ManyToManyField(blank=True, related_name='pages', to='api.link')),
            ],
        ),
    ]
