# Generated by Django 4.0.3 on 2022-04-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='a',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='link',
            name='cname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='link',
            name='country',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='link',
            name='create_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='link',
            name='domain',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='mx',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='link',
            name='ns',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='link',
            name='txt',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='update_date',
            field=models.DateField(),
        ),
    ]
