# Generated by Django 4.0.3 on 2022-04-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_link_a_alter_link_cname_alter_link_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='create_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='update_date',
            field=models.DateField(blank=True),
        ),
    ]
