# Generated by Django 4.0.3 on 2022-04-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_link_create_date_alter_link_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='country',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
