# Generated by Django 4.0.3 on 2022-04-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_link_create_date_alter_link_update_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.URLField(unique=True)),
                ('find_url', models.URLField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='pages',
            field=models.ManyToManyField(blank=True, to='api.page'),
        ),
    ]
