# Generated by Django 4.0.3 on 2022-04-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_link_is_dead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='domain',
            field=models.URLField(blank=True),
        ),
    ]
