# Generated by Django 4.0.3 on 2022-04-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_page_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page',
            field=models.URLField(unique=True),
        ),
    ]
