# Generated by Django 4.0.3 on 2022-04-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_page_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='a',
            field=models.CharField(blank=True, db_column='A', max_length=100),
        ),
        migrations.AlterField(
            model_name='link',
            name='cname',
            field=models.CharField(blank=True, db_column='CNAME', max_length=100),
        ),
        migrations.AlterField(
            model_name='link',
            name='country',
            field=models.CharField(blank=True, db_column='country', max_length=25),
        ),
        migrations.AlterField(
            model_name='link',
            name='create_date',
            field=models.DateField(blank=True, db_column='create_date', null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='domain',
            field=models.URLField(blank=True, db_column='domain'),
        ),
        migrations.AlterField(
            model_name='link',
            name='find_url',
            field=models.URLField(db_column='найденный url'),
        ),
        migrations.AlterField(
            model_name='link',
            name='is_dead',
            field=models.BooleanField(blank=True, db_column='isDead', null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='mx',
            field=models.CharField(blank=True, db_column='MX', max_length=100),
        ),
        migrations.AlterField(
            model_name='link',
            name='ns',
            field=models.CharField(blank=True, db_column='NS', max_length=100),
        ),
        migrations.AlterField(
            model_name='link',
            name='txt',
            field=models.TextField(blank=True, db_column='TXT'),
        ),
        migrations.AlterField(
            model_name='link',
            name='update_date',
            field=models.DateField(blank=True, db_column='update_date', null=True),
        ),
    ]
