# Generated by Django 4.0.3 on 2022-04-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_link_a_alter_link_cname_alter_link_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='domain',
            field=models.URLField(blank=True, db_column='domain', null=True),
        ),
    ]
